name: Publish project to Maven repository
on:
  push:
    branches: [ "master" ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Archive JAR artifact
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: rtp-jar
          path: build/libs/*.jar  # Targets the specific JAR file
          if-no-files-found: error    # Fails the job if no JAR is found
